name: Pull Request
on: pull_request
jobs:
    Pull-Request:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org
                  cache: yarn
            - name: Install and Test
              run: yarn && yarn test
