name: Pull Request
on: pull_request
jobs:
    Pull-Request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 9
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: pnpm
            - name: Install Dependencies
              run: pnpm i --frozen-lockfile

            - name: Test cases
              run: npm test
